### ISSUE TITLE
Demonstration

### ISSUE THREAD

**Issue by Frankie8472** [eth-igl/GP2021-Assignments#55]
What exactly is the demo for? 

First, it took way longer than expected (expected: 3 min, acutal: 10 min). 
I had to show everything that I wrote (and captured via screenshot) in my report but very quickly (no real interaction with the TA). If you are going to read the reports, it doesn't really make sense to me why you wanted to see that without actually discussing my implementation (which is not included in the report).  I would have loved to show my working 😄 

Maybe a better version could be to tell everyone beforehand what they have to show and include how they implemented it. Without a real discussion/interaction with the TA it is also possible to tell them to record themselves via screencap (e.g. obs studio). If you want to measure performance, you could tell the students to use the time.h library and add specific measurements to the report (e.g. time to calculate the horse.off). Let me know what you think! Happy to help and improve 😉

**Comment by wsh312** [comment]
Hi, thanks for your suggestions!
Some thoughts for the next demo:
- Ask the students to show how they organize their code and give points for clean and well-structured code (not sure if students/ETH like to associate points with coding technique).
- Ask the students how a specific feature is implemented and give points for a creative solution.
- Discuss problems faced during the implementation and give points if the student considered more edge cases.
- Design a stress test, give the students some new models to test out.

**Comment by Frankie8472** [comment]
Hi, thanks for your collaboration! 😃 

I assume these are guidelines for the TA's. 
First of all, at all TA's I am not trying to increase your workload! I am sorry if this is the result. It was not my intention to get extra points for my work. While solving a problem I am always asking myself the following: 
- "Is this the right way to implement this?"
- "Is there a simpler way to solve this task?"

I want to learn from mistakes and successes and I cannot expect from you to read through all my code (god forbid). But if you have time in the demos for a discussion, I think it would be beneficial. (An example solution could also totally do it)

**Now:**
For the first point I would be very careful as "clean and well-structured code" is, as you suspected, very subjective. What you could do without implication from ETH/students is check for documentation ("what does this function do, what are the inputs and outputs, does the student know what the function does"). 
For the second point, what is a creative solution? In my opinion this is only in some cases possible, otherwise again I think this is very subjective. You could use the synergy with point one and check if the student understood what he did and possible widen his horizon in telling him a different approach or point out possible mistakes. 
The third point: A great idea!
For the fourth point, I think we have enough models (at least for assignment 2). What do you mean by stress test? Load a huge model and test the speed of your code? It could be enough to let the student run a specific model with specific parameters and measure the time, not? It would then just have to be included in the report (or if the student had problems, discussed in the demosession). 

Setting aside all my thoughts on the demosession, what was your original goal behind it? It is clearly possible that my suggestions are way more what was originaly intended and out of scope (and I am probably way more motivated... 😅). I just did not see the added value in contrast to the report. 

(If by any reason you'd rather have a meeting than to write everything, I am happy to oblige)

**Comment by LeaRe** [comment]
Hello, I read this and would also like to contribute to this discussion, because it’s important to hear different opinions before changing the format of the demo sessions and the grading. I agree with @Frankie8472 that it would be better to know beforehand what to expect from the demo session so the students can come prepared and we can save time during the demo. And also it would be nice to have more time with the TA to ask questions.
But given that all bonus tasks were made mandatory and we also have one mandatory assignment more than last year, I find it not a good idea to introduce even more work for the students in the form of additional stress tests and edge cases that we need to pass during the demo session. I don’t see how this would be beneficial for anyone

**Comment by Frankie8472** [comment]
Thanks, I fully agree. It seems I WAS too motivated and didn't consider all aspects 😅

**Comment by wsh312** [comment]
Thanks a lot for the discussion!

The idea behind my previous thoughts was that all tasks we are asking during the demo should be measurable. I wish we had more resources to appreciate and discuss the outcome of your work. But I don't think we have the capacity to implement them this year, but more for future work.

Yes, we do hear your complaints about the scoring was not transparent enough in the task description. I totally understand if we disclose more detail about our evaluation scheme, it will make the student's life easier. But at the same time, we don't want to discourage the students to explore further and make them only work on what exactly needs to be done rigidly, e.g., only tuning the parameters and models we will examinate. It's like in a normal written/oral exam, the teachers only give a range of important questions, but they hope the students can prepare and learn as much as possible. I believe part of the fun is to make the solution as robust and fast as possible if time and energy allow. 

Another motivation to hide the grading scheme partially is to give ourselves some room to slightly reward those students who do an extraordinary job (e.g., consider many edge cases we didn't think of), and punish mistakes that matter for the future career in general (e.g., the speed is significantly slower than average or crashes unexpectedly). I don't believe any score can measure how good the student is and will be, but I hope it could at least approximately reflect the performance, relative to this pool of students, at this specific task.

I agree showing an example demo could be a good idea! We never give the students the source code of the "master solution" for obvious reasons. But what we could do is showing a video about how the running of a good solution should look like, before or after the demo session. Showing it before might make the task, again, too easy, and showing it after might not be interesting for the students anymore. 

About asking questions face-to-face, instead of github Issue or email, we have a Q&A on 07.05.21, and the students are most welcome to contact the TAs to set up a short discussion session in person. At least for my slow brain, it's hard to do both the basic evaluation and a fruitful discussion within a few minutes during the demo ;)
