### ISSUE TITLE
Assignemnt 3 Bilateral smoothing parameter

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#64]
1 Is sigma_c fixed? If it is fixed, then if the mesh size is uneven there could be no neightbor selected? Or can we use knn and set sigma_c for each point?

2 Is sigma_k defined as the stadard deviation of the edge distance? What if sigma_k = 0 when all edge are equal length should I add a epsilon to it?

**Comment by FloorVerhoeven** [comment]
Hi @boduan1 

Sigma_c is generally the same for everywhere on the surface yes. What you could do is build in a check for this corner case and then double its value whenever no neighbours were found (to prevent crashes when this happens). If you do that make sure though that the value you're using initially for sigma_c isn't too low (i.e. we don't want the majority of the vertices to not be able to find a neighbourhood, it should be the exception). Do you have any mesh specifically where this would be an issue or is it more of a theoretical concern?

Do you mean sigma_s instead of sigma_k? If so, then it's not the standard deviation of the edge lengths. Rather it's the offsets (distances) from the neighbours to the plane defined by the vertex normal of the "central" vertex. See the top right of the second page. This would only ever be 0 when all points in the neighbourhood lie on a plane. You could add a **very small** epsilon to be sure.

**Comment by boduan1** [comment]
> Hi @boduan1
> 
> Sigma_c is generally the same for everywhere on the surface yes. What you could do is build in a check for this corner case and then double its value whenever no neighbours were found (to prevent crashes when this happens). If you do that make sure though that the value you're using initially for sigma_c isn't too low (i.e. we don't want the majority of the vertices to not be able to find a neighbourhood, it should be the exception). Do you have any mesh specifically where this would be an issue or is it more of a theoretical concern?
> 
> Do you mean sigma_s instead of sigma_k? If so, then it's not the standard deviation of the edge lengths. Rather it's the offsets (distances) from the neighbours to the plane defined by the vertex normal of the "central" vertex. See the top right of the second page. This would only ever be 0 when all points in the neighbourhood lie on a plane. You could add a **very small** epsilon to be sure.

Thanks for your explian! It is a theoretical concern, and sorry for my typo...
