### ISSUE TITLE
Assignment 4: LSCM: How to use the gradient matrices?

### ISSUE THREAD

**Issue by MartinaKessler** [eth-igl/GP2021-Assignments#69]
In the assignment sheet it is written that we can use the function computeSurfaceGradientMatrix(D1, D2) in order to compute the LSCM. I don't really see the connection between LSCM and the gradient matrices.

First of all, I would like to make sure that I understand correctly what those gradient matrices D1 and D2 are. Is it correct that an element D1(i,j) contains the derivative in direction 1 (the x-direction?) of triangle i with respect to vertex j?
And D1 & D2 are sparse matrices because the derivative of triangle i is non-zero only for the 3 vertices that belong to the triangle, right?
And the gradient of the triangle i can be obtained by multiplying D1 * V for the x-direction of the gradient, and D2 * V for the y-direction of the gradient?

Secondly, I don't see the why we need those gradients to construct the Jacobian. This is how the Jacobian was derived in class:
![image](https://user-images.githubusercontent.com/79902237/116897331-6bfe3c80-ac35-11eb-9335-daec953d8000.png)
So what is still missing are the vectors e_tilde_T1 and e_tilde_T2. I assume that they must be somehow related to the gradient matrices, but I don't see the connection. Can someone help me and explain this please?

Thanks a lot!

**Comment by Guirec-Maloisel** [comment]
Matrices D1 and D2 correspond to the gradient operator as a whole, not the gradient of a specific function.

First note that taking the gradient is a linear operation (derivative of the sum = sum of derivatives etc). Then remember that a function on a mesh can be discretized into a finite-size vector containing its per-vertex values; and remember from the exercise 4 slides (available on the course webpage) that the gradient of a function on a mesh can be represented by its per-face values (since we use linear interpolation within the faces).

Overall, the gradient of a function on a mesh is a linear operator between two finite-dimensional vector spaces (the per-node and per-face values), so it can be represented in matrix form, which we split into two matrices corresponding to the two partial derivatives for convenience.

For instance, D1 is the matrix of the application mapping per-node values of any function to per-face values of its derivative with respect to the local x coordinate at each point.

If you multiply D1, D2 with X, Y or Z the per-node coordinates, you would get the derivatives of the position function. And if you multiply D1, D2 with U and V you will get the derivatives of the u, v mapping. The four combinations D1U, D1V, D2U, D2V give you the four components of the 2x2 Jacobian.

Finally, for the link with the course notations: the 2x2 Jacobian in the course corresponds to the gradient of the u and the v mapping on a single face. However, in terms of implementation, it is more efficient to compute all gradients for all faces at once with a big matrix product (so using the D1 and D2), but the result for each face is the same. The inverse matrix in your formula is fixed and depends only on the geometry, so it can be precomputed; one row of D1 or D2 corresponds to this precomputation. Note indeed that once this inverse matrix is fixed, the formula is linear in the u and v values.

I hope this helps, don't hesitate to ask if you need more clarifications.
