### ISSUE TITLE
Assignment 4: clarifications on the report

### ISSUE THREAD

**Issue by MartinaKessler** [eth-igl/GP2021-Assignments#71]
I would like to know what you expect us to write in the report:

1) **boundary conditions with 2 vertices:** In the exercise sheet it is written:
> Try to explore various possibilities for picking these two vertices and devise a strategy that will result in nice parameterization (hint: it is a good practice to pick the two most distance vertices as the fixed ones).

Do you require us to show different strategies in the report to get full points or is one strategy enough?

2) **distortion visualization:** In the exercise it is written: 
> Experiment with different criterions (angle preservation, edge length preservation, etc.).

Is it enough to implement angle preservation, edge length preservation and area preservation, or do you expect more to get full points?

3) **ARAP:** Can we just initialize ARAP with the solution of LSCM or do you expect us to initialize it also with the parametrization solution of uniform and cotangent laplacian and show the difference?

4) **optional task:** computation of cotangent laplacian: You announced that assignment 4 will give 19 points. Will this bonus be added to the 19 points? So if we get the bonus and full points in the assignment, we can score 20 points in total?

**Comment by Guirec-Maloisel** [comment]
For the boundary conditions, one strategy is enough as long as you can explain briefly what you did and you get acceptable results with this strategy.

For the visualizations, the three main criteria explore in the assignments (angles, areas, lengths) are sufficient.

The initialization of ARAP is left at your discretion as long as it is reasonable; we do not expect any comparative study of the different options here.

For the optional task on cotan Laplacian, I have to apologize since I didn't notice that task when reviewing the assignment. Your questions from this morning make more sense now. To get both Laplacian computations to match, you have to use the unweighted Laplacian matrix (so no inverse mass matrix, since it removes the symmetry of the matrix). There might be a sign mismatch as well. And to answer your question on the grading, the scores are capped to the announced maximum (19), so the bonus can only help you get the max to this specific assignment.

**Comment by MartinaKessler** [comment]
Thanks for the clarifications! :)
