### ISSUE TITLE
Assignment 4 2.1 flipped triangle

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#74]
I tried to implement 2.1, but some of the triangles seems flipped, is it expected? Or what might be the possible problem?
Thanks!
![image](https://user-images.githubusercontent.com/58148182/117878231-d5212800-b2a5-11eb-8bb5-3eee3fcab95f.png)

**Comment by Guirec-Maloisel** [comment]
If the boundary is fixed to a circle, and the Laplacian weights are non-negative, this should not be happening (Tutte's theorem). As you know, weights in the cotan Laplacian formulation can be negative for obtuse triangles. So you can check if this is what is happening here, and if this disappears when using the uniform Laplacian; or maybe you didn't fix the whole boundary.
Otherwise, there is most probably a problem with your implementation.

**Comment by boduan1** [comment]
Should we use A^T*A or A in the formula?
I changed A^T*A to A in the matrix and get a good result.
 
![image](https://user-images.githubusercontent.com/58148182/117964184-99c43f00-b321-11eb-95e5-705145b8f03c.png)

**Comment by Guirec-Maloisel** [comment]
For this task there is no need for A^T, the formula is in the case of the next tasks where you will obtained an overconstrained (and thus non-square) linear system, which you need to solve in a least-squares sense. Here the Laplacian matrix is already square, so no need for this.

**Comment by boduan1** [comment]
Thanks!
