### ISSUE TITLE
Assignment4 free boundary

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#75]
In free boundary condition can we set the two constraint points to (0,0) and (0,1)?
I understand that in 2.3 the error also depend on the scale, in this case should we change the scale of the two constraint points?

**Comment by Guirec-Maloisel** [comment]
The exact choice of constraint is not important; although for comparison with the other constraints it might make sense to pick to opposite points on the unit circle.
Since the boundary is free, if meaningful points are picked for the constraint, the algorithm should be able to get good results regardless of scale issues most of the time. When that is not the case you can use the +/- keys to scale up or down the texture pattern so you can still visualize the distortion.

**Comment by boduan1** [comment]
I don't think so. For example, in length distortion, if we have original mesh large triangle, and we map it to small triangles we will have large error, and the optimize might not work well?

**Comment by Guirec-Maloisel** [comment]
In terms of results, if there is some uniform scaling happening it does not really matter as you can just scale the texture; what counts is the relative length scaling of different triangles.

In terms of algorithm, as you noted if we ask for something very extreme, mapping the jacobians to rotations might not make sense; you would have to adapt the size of the circle to which we map selected points, or to scale the model first. But with the meshes provided in the assignment you should not have too extreme scaling problems.

**Comment by boduan1** [comment]
Thanks! bunny.off seems have a different scale
