### ISSUE TITLE
Assignment 5 Deformation Transfer

### ISSUE THREAD

**Issue by boduan1** [eth-igl/GP2021-Assignments#83]
I am very confused with the paper, could you provide some steps of implementation and give some explanation to help understanding?

I also have some questions:

1 Now I understand to first compute G,D,S and  use (14) to solve p', is this correct?

In (14)
![image](https://user-images.githubusercontent.com/58148182/118569834-06549900-b77b-11eb-978f-528c783c38b6.png)

2 How to compute G matrix? Is there a library to compute it?

3 What is the D matrix? I understand it as diag(a1,a1,a1,a2,a2,a2...am,am,am) where ai is the area of triangle i, is this correct?

![image](https://user-images.githubusercontent.com/58148182/118569169-ac070880-b779-11eb-9b14-44c1a76a9bb2.png)

4 Is qi,qi',n,n' in S,S' or in B,B'? If it is S,S' we have both the unknow value from S' in both side of the equation (14), how to solve it? And we don't use B,B' anywhere?

5 Is the G,D matrix also fixed for all steps during further deformation?

**Comment by FloorVerhoeven** [comment]
The paper provides an alternative way to preserve details during mesh deformation, i.e. how to go from B' to S', see also Fig. 2 in the paper (an alternative to what you implemented for part 1.4 of the assignment). 
They do this by solving a Poisson problem (eq. 14) which builds on the fact that we're trying to find p' such that Gp' = S, i.e. the gradient of the new triangle coordinates should match the known per-triangle deformation gradients S that correspond to the deformation from B to B'.

For your questions:
1) Yes, correct. You want to use substitution again like for part 1 (i.e. only solve for the free vertices and subtract corresponding part for the known positions from the right-hand side).
2) G is the gradient operator, you can use `igl::grad()` for it.
3) D contains the face areas indeed. Because of how igl constructs the gradient operator G it's easiest to instead make D= drag(a1,a2..am,a1,a2...am,a1,a2,...,am). Check out the functions `igl::diag()` and `igl::repdiag()`.
4) qi' and n' are in B', qi and n are in B. I just now spot they have a typo about this in the paper, sorry about that, I'll make a post about it.
5) Yes, G and D stay fixed during the deformation steps and can be precomputed, only S_j needs to be recomputed every time.

**Comment by boduan1** [comment]
> The paper provides an alternative way to preserve details during mesh deformation, i.e. how to go from B' to S', see also Fig. 2 in the paper (an alternative to what you implemented for part 1.4 of the assignment).
> They do this by solving a Poisson problem (eq. 14) which builds on the fact that we're trying to find p' such that Gp' = S, i.e. the gradient of the new triangle coordinates should match the known per-triangle deformation gradients S that correspond to the deformation from B to B'.
> 
> For your questions:
> 
> 1. Yes, correct. You want to use substitution again like for part 1 (i.e. only solve for the free vertices and subtract corresponding part for the known positions from the right-hand side).
> 2. G is the gradient operator, you can use `igl::grad()` for it.
> 3. D contains the face areas indeed. Because of how igl constructs the gradient operator G it's easiest to instead make D= drag(a1,a2..am,a1,a2...am,a1,a2,...,am). Check out the functions `igl::diag()` and `igl::repdiag()`.
> 4. qi' and n' are in B', qi and n are in B. I just now spot they have a typo about this in the paper, sorry about that, I'll make a post about it.
> 5. Yes, G and D stay fixed during the deformation steps and can be precomputed, only S_j needs to be recomputed every time.

Thanks for your explaination. Sorry I am still some problem.
1 Do we solve the full system for n points and then extract the free points? Or do we first extract the free points and correspoinding G,D,S and solve the subsystem?

3 In this case do we need to change the order of S matrix in (14) to make it 
( S1^T.row(0),...,Sm^T.row(0),S1^T.row(1),...,Sm^T.row(1),S1^T.row(2),...,Sm^T.row(2) )

**Comment by FloorVerhoeven** [comment]
1) You should solve the subsystem for the free points only (similar to slide 15 from the exercise session, except now with a different matrix A and a right hand side that isn't supposed to be equal to 0)
2) Yes, that's right

**Comment by boduan1** [comment]
> 1. You should solve the subsystem for the free points only (similar to slide 15 from the exercise session, except now with a different matrix A and a right hand side that isn't supposed to be equal to 0)
> 2. Yes, that's right

Thanks!
