### ISSUE TITLE
Assignment Point Distribution Feedback

### ISSUE THREAD

**Issue by nwicki** [eth-igl/GP2021-Assignments#89]
(It is probably a bit late to make a remark about that, but for the most time it did not bother me too much.)

Why was the point distribution so far not available on the assignment sheets? Afaik most of the other courses I take provide the possible points achievable per assignment and task.

This way, couldn't you theoretically assign the last task of each assignment 100% of the points and none to the others?

**Comment by FloorVerhoeven** [comment]
HI @nwicki 

We of course try to make a fair point distribution for each assignment, taking into account the difficulty and size of the subtasks. With the course going up to 8 ECTS this year and the exam falling away due to COVID-19, we've made some changes/additions to the assignments compared to previous years. Especially with new tasks we've wanted to make sure that there weren't any problems/difficulties that we didn't foresee.

That being said, I naturally understand that as a student it is very helpful to know the point distribution within each assignment. We'll definitely discuss providing a more detailed point distribution for the subtasks for next year.
